# location / {
#    proxy_pass http://%upstream%;
#    include %proxyFolder%/proxy.conf;
# }

location / {
    default_type application/json;
    include %proxyFolder%/proxy.conf;
    return 200 '{"welcome_to":"%domain%"}';
}