include %appFolder%/upstream.conf;

server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name %domain%;
        include %appFolder%/main.conf;
}

server {

        listen 80;
        listen [::]:80;
        server_name .%domain%;

        # logging
        access_log %logFolder%/%domain%.access.log;
        error_log %logFolder%/%domain%.error.log warn;

        # additional config
        include %proxyFolder%/letsencrypt.conf;

        # reverse proxy
        location / {
                return 301 https://%domain%$request_uri;
        }
}
