/**
 * DNS-challenge command — internal command called by certbot hook scripts.
 *
 * NOT shown in `--help` (desc is set to false). This command handles
 * the actual DNS API calls to create or delete TXT records during
 * a DNS-01 ACME challenge. It's invoked by the auth-hook and
 * cleanup-hook shell scripts generated by `dns-setup`.
 *
 * @packageDocumentation
 */

import path from "path";
import { CommandBuilder } from "yargs";

import { DnsProviderName, ICommonArgs, LogLevel } from "../types";
import { Logger } from "../logger";
import { Shell } from "../shell";
import { ProxyBuilder } from "../builder";
import { getProvider, loadProviders } from "../dns/provider";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** CLI arguments for the internal dns-challenge command. */
interface IDnsChallengeArgs extends ICommonArgs {
    /** "create" to add TXT record, "cleanup" to remove it. */
    action: string;
    /** The domain being certified (CERTBOT_DOMAIN). */
    domain: string;
    /** The validation token (CERTBOT_VALIDATION). */
    token: string;
    /** DNS provider name. */
    provider: DnsProviderName;
}

// ---------------------------------------------------------------------------
// Command Export
// ---------------------------------------------------------------------------

export const command = "dns-challenge";

/** Hidden from --help — this is an internal command. */
export const desc = false;

export const builder: CommandBuilder = {
    action: { type: "string", demandOption: true, description: "create or cleanup" },
    domain: { type: "string", demandOption: true, description: "CERTBOT_DOMAIN" },
    token: { type: "string", demandOption: true, description: "CERTBOT_VALIDATION" },
    provider: { type: "string", demandOption: true, description: "DNS provider name" },
};

/**
 * Handler for the internal `dns-challenge` command.
 *
 * Creates or deletes TXT records via the configured DNS provider API.
 * Called by certbot hook scripts during DNS-01 challenges.
 *
 * @param argv - Parsed CLI arguments.
 */
export const handler = async (argv: IDnsChallengeArgs): Promise<void> => {
    const logLevel = argv.verbose ? LogLevel.DEBUG : argv.quiet ? LogLevel.QUIET : LogLevel.INFO;
    const logger = new Logger(logLevel);
    const shell = new Shell(logger, false);
    const target = path.resolve(argv.target);

    // Load config to get stored DNS credentials.
    const proxyBuilder = new ProxyBuilder(target, logger, shell);
    const config = proxyBuilder.loadConfig();

    if (!config) {
        logger.error("Config not found");
        process.exit(1);
    }

    // Load DNS providers and get the requested one.
    loadProviders();
    const provider = getProvider(argv.provider);

    if (!provider) {
        logger.error(`Unknown DNS provider: ${argv.provider}`);
        process.exit(1);
    }

    // Get stored credentials for this provider.
    const credentials = proxyBuilder.getConfigManager().getDnsCredentials(argv.provider);

    if (!credentials) {
        logger.error(`No credentials configured for ${argv.provider}. Run 'dns-setup' first.`);
        process.exit(1);
    }

    const recordName = "_acme-challenge";

    try {
        if (argv.action === "create") {
            logger.info(`Creating TXT record for ${argv.domain}...`);
            await provider.createTxtRecord(argv.domain, recordName, argv.token, credentials);
            logger.success("TXT record created");
        } else if (argv.action === "cleanup") {
            logger.info(`Removing TXT record for ${argv.domain}...`);
            await provider.deleteTxtRecord(argv.domain, recordName, argv.token, credentials);
            logger.success("TXT record removed");
        } else {
            logger.error(`Unknown action: ${argv.action}. Expected "create" or "cleanup".`);
            process.exit(1);
        }
    } catch (err: unknown) {
        const message = err instanceof Error ? err.message : String(err);
        logger.error(`DNS challenge failed: ${message}`);
        process.exit(1);
    }
};
