# SSL certificates for %domain%
ssl_certificate     %sslFolder%/live/%domain%/fullchain.pem;
ssl_certificate_key %sslFolder%/live/%domain%/privkey.pem;
ssl_trusted_certificate %sslFolder%/live/%domain%/chain.pem;
