name: BuildTestDeploy
on:
    push:
        branches:
            - "*" # matches every branch that doesn't contain a '/'
            - "*/*" # matches every branch containing a single '/'
            - "**" # matches every branch
jobs:
    BuildTestDeploy:
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: queue work
              if: always()
              run: work_queue queue ${{ github.event.organization.login }}_${{ github.event.repository.name }}

            - name: Installing Packages
              run: |
                  yarn install

            - name: Building the Project
              run: |
                  yarn build

            - name: Publish packages
              run: |
                  git reset --hard
                  yarn tag-version-auto --yes
                  yarn publish-packages --yes

            - name: clear work queue
              if: always()
              run: work_queue clear ${{ github.event.organization.login }}_${{ github.event.repository.name }}
